image:
  file: .devcontainer/Dockerfile

ports:
  - port: 8000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: ignore

tasks:
  - init: |
      composer install
  - before: |
      sudo chmod -R 777 /workspace/.gitpod
      sudo chmod -R 777 /workspace/.vscode-remote
  - command: php -S 0.0.0.0:8000
