version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .gitpod.Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      GITPOD_WORKSPACE_URL: ${GITPOD_WORKSPACE_URL}

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paradigmshift
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
