version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .gitpod.Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      GITPOD_WORKSPACE_URL: ${GITPOD_WORKSPACE_URL}

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: afjcardiff
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""

volumes:
  mysql-data:
